// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AppShellController from "./app_shell_controller"
application.register("app-shell", AppShellController)

import DesignSystemController from "./design_system_controller"
application.register("design-system", DesignSystemController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ScrollVideoController from "./scroll_video_controller"
application.register("scroll-video", ScrollVideoController)

import SeamlessLoopController from "./seamless_loop_controller"
application.register("seamless-loop", SeamlessLoopController)
